# Generated by Django 4.1.7 on 2023-03-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='endTime',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
